# Build website
[build]
command = "yarn run build"
publish = "dist"

# SPA redirect
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Terry Pratchett homage
[[headers]]
for = "/*"
[headers.values]
X-Clacks-Overhead = "GNU Terry Pratchett"
